### PR TITLE
Added entities folder and Bracket.java

### PR DESCRIPTION
**Pull request by SpaceJesusTM**
Just a test to review the GitHub development process.

### CODE REVIEW

**Review by minjaedavidpark — APPROVED** [review]
looks great

**Review by HanliJiang13 — APPROVED** [review]
Good

**Comment by yibinglu** [comment]
tester

**Review by yibinglu — APPROVED** [review]
good

**Review by Kelleou — APPROVED** [review]
Good

**Review by yibinglu — APPROVED** [review]
test

**Pull request merged**
