### PR TITLE
12 feature 11 advance a team to the next round

### PR DESCRIPTION
**Pull request by AdK0101**
NOTE: Since I work on three different, similar features (advancing a winner, declaring a winner, and changing the points for a team), and I occasionally pulled from branches other than this one, some of the commits on this branch are not directly related to the development of this feature – partially to test things informally, simply for conveniance. However, the main development on this branch was relating to advancing a team. Also note that when it says there are three participants, that does not mean that the other two group members (Samuel, Nicholas) wrote code for this feature - rather I pulled code into this branch that they wrote for a _different feature._  This can be seen in the commit history. 

This is a pull request for the feature relating to advancing a team once a game has been completed. All of the backend has more or less been completed. This pull request contains the following new classes in the use case layer: AdvanceTeamUC (the use case interactor), AdvanceTeamID (the input data/request model), AdvanceTeamOD (output data/response model), AdvanceTeamIB (input boundary), and AdvanceTeamOB (output boundary). This was designed to be in line with clean architecture. The input takes the bracket ID, username, and game ID from user input, and is passed into the interactor’s advanceWinner method (via the output boundary). Here, the use case does the following: provided all of the necessary conditions are met, the winning game's winning team is advanced to the next round (/placed in the following node of the tournament tree). The output data packages and brings the data out to the presenter. 

I have also made a draft of the controller, and presenter. These may need to be slightly modified once we get a better understanding of the view. But for the time being, it should be a working draft. Finally, I have also implemented a very crude form of persistence (which I have tested informally). The classes related to it are the AdvanceTeamDSID (database request model), which is passed in via the gateway interface to the AdvanceTeamFileWriter, which saves the data. 

Things do add later
1. I have some very minor documentation. I will add more javadocs later. 
2. I have sequestered some common algorithms relating to tree traversal and checking user permissions under the generalClasses package. This was to attempt to adhere to SOLID closer by implementing something similar to the strategy design pattern, but not exactly the same. I will likely try to refactor my code later to make the design pattern more explicit/proper. 
3. I have tested informally. But I have not written formal unit tests. I will do that later. 

Other notes: one design decision I made, was for the new game to which the winning team is advanced, the assigned observer will be the observer from the previous round. We can change this later. This is just a make-shift idea because we did not have a well-defined way of doing this before.

### CODE REVIEW

**Review by yibinglu — DISMISSED** [review]
This PR looks good, again very similar to your other two features so I will just comment on the main difference here which is the insertTeam method in the use case. Since you said you've done some informal testing, I trust that it works but I was just wanting some more clarification (also something to consider when adding more documentation for the project itself). I was a little confused by the sentence "That is, the current round plus 1 - rounds are counted backwards in the tree". I see that in the parameters of returnLevelGames, the second parameter is this.game.getGameRound() + 1 so I'm a little confused about how it's counting "backwards". One more small thing, in this line "Find the node in tree s.t. its previous node(1/2) == game" what does it mean by node(1/2)?

**Review by yibinglu — APPROVED** [review]
Same change as https://github.com/CSC207-2022F-UofT/course-project-group65/pull/30

**Review by SpaceJesusTM — DISMISSED** [review]
I won't write too much as I have informally already looked over this code and we have discussed what needs to be done. The only major issue that needs to be changed for our first-hand-in is input data, as the button will only give you the game ID. The current user's name and bracket ID are given by the previous use case through either the output data or Next Screen data and is added to the UC when it is constructed (parameters to the constructor). Other than that the logic should follow and all that's left is to connect this to the front end, as well as create the game view screen. Any other changes to backend that need to be done will be done in the front end branch, but documented clearly as a backend change.

**Review by Nicknames43 — DISMISSED** [review]
Overall, this pull request looks good and I can see that your implementation follows CA and SOLID. This use case is very similar to your other feature that I reviewed so I won't go into much detail. This is also the branch that I would pull from when we had an overlap in our code so I already have a general level of familiarity with this feature. The only change I can see is with the input data as Samuel had brought up.

**Review by SpaceJesusTM — APPROVED** [review]
Fixing merge issues as a team, same comments apply see above.

**Review by yibinglu — APPROVED** [review]
Conflict merge approved

**Review by Nicknames43 — APPROVED** [review]
fixed merge issues as a team.

**Pull request merged**
