### PR TITLE
5 feature 7 joining the team

### PR DESCRIPTION
**Pull request by HanliJiang13**
This pull request follows the Clean Architecture for backend implementations of the joinTeam feature. The joinTeam use case layer includes joinTeamIB(input boundary), joinTeamID(input data), joinTeamOB(output boundary), joinTeamOD(output data), and joinTeamUC(use case interactor).

The functionality of this feature is to let the user to join an existed team, before that it will check whether the user is player, whether the team exists, and whether the team has already reached its maximum size. Then add the user to the teamMembers which is a list for that team's members if all the checks passed.

The input data takes in two variables user and team name from that user, and we have the getters and setters for both variables. The use case interactor implements the input boundary and have the method joinTeam() which did the functionality I mentioned above. If the checks did not pass, the use case will prepares a fail view to let user know which check did not pass. If all the checks passed, then output data packages data include: success message, username for the user, updated teamMembers, and updatedBracket.

### CODE REVIEW

**Review by SpaceJesusTM — APPROVED** [review]
Code packaging and structure follow our general format which is good, small thing we may just change the name to JoinTeam... just to keep constant with the naming scheme, but that is a small detail. In terms of the input data, you will only be receiving what team the user is trying to join and not the User. The username is given by initializing the use case (which you have currently) however you need to use the account repo to find the actual user.

On a more important change, the output data should not return a list of users or the Bracket as that would violate clean architecture. Instead, the bracket is changed and should just remain untouched and then you should return an ArrayList with the usernames of everyone on the team. This is then used to update the corresponding team list in the bracketView screen (as a side note, in general, if you need some data from the bracket to update the view, you should extract that data and package it, NOT package the bracket itself.)

Another thing, you don't need to check if the team is null as we have a default value of a blank team assigned when the bracket is created. However, you do have to check if the team name is something like "BlankTeam _" and if it is you have to raise an error letting the user know this team is not joinable. (See my UC when I create the new Bracket/screen for details)

Other than that we should be fine for now, and we can work towards connecting everything together. I will be approving this so we can begin working on the front end (see issues), however, please implement these changes and cross-check it with the other branches.

**Review by AdK0101 — APPROVED** [review]
Generally speaking, the layers in clean architecture are well-defined in your work. So that is good. A couple of notes though. In your use case file, I notice that you have both checkTeamExistence and findTeam. 

One thing you could do, is make team into an attribute. So findTeam would only set this.team = team. That way, instead of the method returning a team, it could return a Boolean determining whether the team was found or not. This way, it shortens your code by essentially combining checkTeamExistence and findTeam into one. Then all you’d do is that in the joinTeam method, if that method returned false, then you return the failView. 

Other than the change that needs to happen with the output data – which has already been noted in a different code review, your work looks fine. Make sure to add documentation and tests later.

**Review by minjaedavidpark — APPROVED** [review]
It has every element necessary for Clean Architecture and the packaging structure is good.
Use of getters and setters whenever needed is appropriate.
In terms of naming convention, change the first letter of all your classes to capital letter for consistency as Sam said.
Other details that should be fixed are mentioned above in Sam and Aditya's comments. Please make sure to follow the Clean Architecture in your code as the structure is the number 1 priority for our project.
I will approve it for now as we need the code. Thanks for your work!

**Comment by HanliJiang13** [comment]
To do list for myself from the comments above:

1.  change the classes' names to JoinTeam.
2.  change the input data to only the team user wants to join.
3.  change the output data -  should not return teamMembers or the Bracket. And change the code for that.
4.  change the method for findTeam and check methods.
5.  add documentation and tests

**Pull request merged**
