### PR TITLE
Repackaging for CA

### PR DESCRIPTION
**Pull request by AdK0101**
## Pull Request Title and Description
This was principally about repackaging all of our classes to fit clean architecture. 

## Changes Made
All the files have been repackaged as needed. 

## Design Patterns
None.

## Clean Architecture and SOLID
None.

## Additional Changes, Comments, and Questions
None.

## PR Checklist
- [Yes ] I have pulled all existing changes and included them with my new changes.
- [Yes ] I have addressed all IntelliJ "red" issues or have documented them above.
- [ Yes] I have filled in each of the above sections.
- [Yes ] I have contacted the reviewers and any other relevant group members.

### CODE REVIEW

**Review by SpaceJesusTM — DISMISSED** [review]
We discussed the repackaging changes and processes before these changes were implemented. This fixes our CA packaging issues therefore an improvement over the old packaging format.

**Review by Nicknames43 — DISMISSED** [review]
approved

**Review by HanliJiang13 — APPROVED** [review]
Approved

**Review by Kelleou — APPROVED** [review]
Approved.

**Review by SpaceJesusTM — APPROVED** [review]
See previous comment.

**Review by Nicknames43 — APPROVED** [review]
approved again

**Pull request merged**
