### PR TITLE
Features 1 & 2: Create an account and login

### PR DESCRIPTION
**Pull request by yibinglu**
This pull request is for all the backend use case implementations for user account creation and logging in.

NOTE: Originally, creating an account and logging in were going to be two separate pull requests, but due to some Git issues, it was more efficient to create a pull request for the one branch that had the most up-to-date information which was the login branch.

### Account Creation
Following the example repo from the lecture, the use case layer includes CreateAccountIB (input boundary), CreateAccountID (input data), CreateAccountOB (output boundary), CreateAccountOD (output data), and CreateAccountUC (use case interactor).  

The input data takes in the username and password from the user and has setters and getters for both. The use case interactor implements the input boundary which in this case includes the method create() which is what is creating a new user. The use case also checks whether or not the username already exists and if it does, prepares a fail view. The output data packages the data, in this case, the username and password, from the use case. 

### Log In
Like account creation, the use case layer consists of LogInIB (input boundary), LogInID (input data), LogInOB (output boundary), LogInOD (output data), and LogInUC (use case interactor).  

Creating an account and logging in follow a very similar CA structure, see above. There are a few key differences though. In the use case, instead of creating a new user, its main function is to check if the username exists and the password matches and returns whether or not the user can then be logged into the bracket. The output data also does not include the password and instead had the user's role in the bracket (which would be an empty hashmap if this is their first time logging in) as well as the current tournament they are in,

### CODE REVIEW

**Review by SpaceJesusTM — DISMISSED** [review]
In terms of code organization and style, everything looks good. However, there is one major issue and one minor issue.

1. I see the UserFactory which is great as it allows for extension, however it is just an interface and is not implemented anywhere. As such we aren't actually creating any instances of the DefaultUser class. Additionally in the CreateAccountUC, unless I missed it the new account is not stored in the AccountRepo which means it is lost once the Use Case ends. This is a major issue and should be addressed ASAP.

2. In each Use Case please have the repositories, Account, and Bracket repo as attributes to the UC classes, this means having them as part of the constructor so this information is inputted when creating an instance of this UC. Additionally, make sure both Account/Bracket repo along with the currently logged-in user is passed as output data as the next view needs this information to initialize the following use case classes.

Later we will need to add tests and Javadocs to ensure everything is functioning as intended, however, this is something everyone needs to complete. I will be approving this pull request as we need all the current information to start working on connecting the front end, however, it is crucial the issues outlined are addressed before our first hand-in.

**Review by AdK0101 — APPROVED** [review]
First of all, clean architecture is followed, and good use of the factory design pattern for the user. It makes the program generally quite extendible, which is always good. One thing you could argue is a code smell, is the long parameter list for logInResult. One way to fix this, is to have the constructor take the repos, and then assign them to an attribute within the class. This should make the code look cleaner. That also means making a constructor for the log in use case, which is currently missing right now. As Samuel has mentioned, do this for the create account use case as well. Make sure that the updated repositories are passed into the output data as well for the reasons Samuel has mentioned. 

Other than that, the code is generally quite modular, which is good. Aside from adding javadocs and testing, I do not see any other issues besides those mentioned. I approve.

**Review by minjaedavidpark — APPROVED** [review]
Overall, the packaging and structure of the code look good as it adheres to Clean Architecture.  Each level of layer is separated as needed.

Also, I see that you implemented UserFactory and added the code to add the user information to the AccountRepo, which is great because as Sam said this was really important.
As mentioned above, adding repositories like AccountRepo to each UC should be necessary.
For your commented line for LoginResult in LoginUC, I think we may want NO_SUCH_USER since we may want to differentiate between cases where the user just got their password wrong and where the user with the given username does not exist, but the decision is up to you.
One question is, don't we need a controller for CreateAccount as well? I don't see that in the screen package. I assume you are working on the front-end things now and you will get them done soon.
Other than that, all the back-end things seem fine for now. I will approve your request.

**Review by SpaceJesusTM — DISMISSED** [review]
For some reason, it did not count my review (accidentally request a re-review), the following is the same as the last comment:

In terms of code organization and style, everything looks good. However, there is one major issue and one minor issue.

I see the UserFactory which is great as it allows for extension, however it is just an interface and is not implemented anywhere. As such we aren't actually creating any instances of the DefaultUser class. Additionally in the CreateAccountUC, unless I missed it the new account is not stored in the AccountRepo which means it is lost once the Use Case ends. This is a major issue and should be addressed ASAP.

In each Use Case please have the repositories, Account, and Bracket repo as attributes to the UC classes, this means having them as part of the constructor so this information is inputted when creating an instance of this UC. Additionally, make sure both Account/Bracket repo along with the currently logged-in user is passed as output data as the next view needs this information to initialize the following use case classes.

Later we will need to add tests and Javadocs to ensure everything is functioning as intended, however, this is something everyone needs to complete. I will be approving this pull request as we need all the current information to start working on connecting the front end, however, it is crucial the issues outlined are addressed before our first hand-in.

**Review by AdK0101 — APPROVED** [review]
Changes are okay now.

**Review by SpaceJesusTM — APPROVED** [review]
Changes I specified were made, any other changes we will proceed to make in the next versions. See previous comment for more.

**Review by HanliJiang13 — APPROVED** [review]
Good, it's ready to merge.

**Review by Kelleou — APPROVED** [review]
good

**Pull request merged**
