### PR TITLE
8 feature 4 joinview tournament

### PR DESCRIPTION
**Pull request by Nicknames43**
This is a pull request for the feature(s) relating to allowing a user to join a new tournament or view a tournament they have previously joined. This was designed using the principles of clean architecture. 

### JoinTournament
This pull request contains the following new classes in the use case layer: JoinTournamentUC (the use case interactor), JoinTournamentID (the input data/request model), JoinTournamentOD (output data/response model), JoinTournamentIB (input boundary), and JoinTournamentOB (output boundary).

The input data takes the invite code for the tournament. The interactor implements the input boundary and does the following: provided all necessary conditions are met, the user becomes either an observer or player of the tournament corresponding to the invite code, and the user is brought to the main tournament view page. The output data packages and brings data out to the presenter.

### ViewTournament
This pull request contains the following new classes in the use case layer: ViewTournamentUC (the use case interactor), ViewTournamentID (the input data/request model), ViewTournamentOD (output data/response model), ViewTournamentIB (input boundary), and ViewTournamentOB (output boundary). 

The input data takes the tournamentID. The interactor implements the input boundary and does the following: provided all necessary conditions are met, the user is brought to the main tournament view page. The output data packages and brings data out to the presenter.

### CODE REVIEW

**Review by yibinglu — APPROVED** [review]
NOTE: I think you may have a small typo in your PR, I'm assuming the second header should say ViewTournament instead of JoinTournament. You should still be able to go back and edit it, if not, it's not a big deal.

Looking at JoinTournament, everything looks about right, CA seems to be implemented and overall functionality seems solid. My only question is about when the error message "Role does not exist within tournament" would come up. Since the users are inputting roles themselves, when would we have a case where their role isn't valid?

**Review by SpaceJesusTM — APPROVED** [review]
I won't write too much as the logic for this UC seems to follow our design, we will have to see how it works when connected to everything else. However, note that output data for this use case will be ALL THE VISUAL DATA OF THE TOURNAMENT YOU ARE JOINING. When joining an existing tournament or any tournament for that matter, we do not know how far along it is. So we have to work with the assumption that everything needs to be updated to the live view. As such make sure your output data is consistent with all the setter functions in the bracket View. This is something that is easier to see once everything is up and working so we I will approve the merge so we can more easily work on these changes.

**Review by AdK0101 — APPROVED** [review]
Everything looks generally fine and seems to be in accordance with clean architecture and solid principles. As well, the code is clean and the logic is easy to follow. If I see any issues that have not been stated by other code reviewers later, I will let you know personally.

**Comment by Nicknames43** [comment]
> NOTE: I think you may have a small typo in your PR, I'm assuming the second header should say ViewTournament instead of JoinTournament. You should still be able to go back and edit it, if not, it's not a big deal.
> 
> Looking at JoinTournament, everything looks about right, CA seems to be implemented and overall functionality seems solid. My only question is about when the error message "Role does not exist within tournament" would come up. Since the users are inputting roles themselves, when would we have a case where their role isn't valid?

For the JoinTournament, the role is determined by the role key from the invite link. So this error would only appear if the tournamentID part of the invite code is correct and the user hasn't joined the tournament before but the part of the invite link is not one of "PL" or "OB". It's basically just there to signal which part of the invite code the user input is incorrect.

**Pull request merged**
