### PR TITLE
Repackaging

### PR DESCRIPTION
**Pull request by SpaceJesusTM**
## Pull Request Title and Description
Include the branch you were working on and a high level description of the changes.
FINAL PULL REQUEST

## Changes Made
Include a list of the files changed. For each file include a decription of the change and any relevant techincal details.
Changes to the ReadMe
Adding control buttons
Adding Comments for better description
Cleaning up code
Removing Yellow warnings (except for ones that are documented)
Deleting unused files

## Design Patterns
If any Design Patterns of have been used or altered, please give a description of the pattern as well as it's relevance to the overall project.'
Removed strategy design pattern

## Clean Architecture and SOLID
If any new files have been created or moved, please include a description of where this fits in CA. If you made any changes that have 
relevance to SOLID please include a decsription here. Additionally, if there is any probelms with CA or SOLID that you have identified
please include the problem description here.
N/A

## Additional Changes, Comments, and Questions
If you have any additional comments or questions please include those here. If you need changes made to files being worked on by 
a group member please include the change descrpition here with the member that must make the change. Additionally, contact and document
the change on the project Discord so all group members are notified.
Good Work Team, let's FINISH STRONG

## PR Checklist
- [x] I have pulled all existing changes and included them with my new changes.
- [x] I have addressed all IntelliJ "red" issues or have documented them above.
- [x] I have filled in each of the above sections.
- [x] I have contacted the reviewers and any other relevant group members.

### CODE REVIEW

**Review by HanliJiang13 — APPROVED** [review]
Final approved

**Review by minjaedavidpark — APPROVED** [review]
APPROVED

**Review by Kelleou — APPROVED** [review]
Good

**Review by yibinglu — APPROVED** [review]
Looks good

**Pull request merged**
