### PR TITLE
7 feature 9 change points for a team

### PR DESCRIPTION
**Pull request by AdK0101**
NOTE: Since I work on three different, similar features (advancing a winner, declaring a winner, and changing the points for a team), and I occasionally pulled from branches other than this one, some of the commits on this branch are not directly related to the development of this feature – partially to test things informally, simply for convenience. However, the main development on this branch was relating to changing points. Also note that when it says there are three participants, that does not mean that the other two group members (Samuel, Nicholas) wrote code for this feature - rather I pulled code into this branch that they wrote for a _different feature._  This can be seen in the commit history. 

This is a pull request for the feature relating to allowing the observer or overseer to change the points that a team has within a game. All of the backend has more or less been completed. This pull request contains the following new classes in the use case layer: ChangePointsUC (the use case interactor), ChangePointsID (the input data/request model), ChangePointsOD (output data/response model), ChangePointsIB (input boundary), and ChangePointsOB (output boundary). This was designed to be in line with clean architecture. The input takes the bracket ID, username, points to be added, game ID, and the team name from user input, and is passed into the interactor’s changePoints method (via the output boundary). Here the use case does the following: provided all of the necessary conditions are met, the points that the overseer/observer wants to add, is added to the team. The output data packages and brings the data out to the presenter. 

I have also made a draft of the controller, and presenter. These may need to be slightly modified once we get a better understanding of the view. But for the time being, it should be a working draft. Finally, I have also implemented a very crude form of persistence (which I have tested informally). The classes related to it are the ChangePointsDSID (database request model), which is passed in via the gateway interface to the ChangePointsFileWriter, which saves the data. 

Things do add later
1. I have some very minor documentation. I will add more javadocs later. 
2. I have tested informally. But I have not written formal unit tests. I will do that later. 

Other notes: I deleted a number of files in my branch prior to pull requesting (those that were unnecessary), so my last few commits may show up as having failed the github autograding, even though the code should work fine.

### CODE REVIEW

**Review by yibinglu — DISMISSED** [review]
Overall, seems like there are no major issues. Your code follows clean architecture and SOLID principles which is what we needed. I just have a few clarifying questions, you can just respond to them as comments in the PR and I'll take a look.

1. Perhaps this is a misunderstanding on my part on how the point system work for our program but how come we have both checkGame and checkTeam? I was under the impression that we were only going to be incrementing the points for the teams and once the teams themselves reached a certain number of points, they would be advanced into the next round.

2. For the checkObserverAssigned method, it seems like it's checking if the current user is the assigned observer for this team and if they're not, it displays "You are not assigned to the game". Does this apply to any user who's in the bracket regardless of their role? Because if so, I think it would make more sense to have a check that sees whether or not the current user's role is observer first. For example, it would be confusing for someone of a Player role to receive this error message.

As I said, I think your changes are valid so I'll approve this PR, if anything changes, just let the group know and we can go ahead and merge it.

**Comment by AdK0101** [comment]
Regarding the first question, the reason we have both a checkGame and checkTeam function is more of a sanity check and for extensionality. Realistically with our implementation, all we need is a checkTeam function, but for extensionality purposes, I added the checkGame function just in case someone else ever wanted to change how this use case worked - in which case this would have to be checked. Informally, the reason we have a checkGame, is that we can only add points to a team in a game, if the game exists. 

As for the second question, you're actually right. This is a small change that I made really quickly last night which is why this might have slipped my mind. I'll make the change soon.

**Review by yibinglu — APPROVED** [review]
Ok, that makes sense, and the change to observer assignment looks good now.

**Review by Kelleou — DISMISSED** [review]
Similar to DeclareWinner, this usecase follows clean architecture.
Again, I am not too sure about whether InputData shoud have all the IDs as I am not sure if the observer can see them on his/her screen(I have mentioned this in my review for DeclareWinner).
I just have some advice for ChangePointsUC.
In ChangePointsUC, before the points can be changed, there are several checks that changePoints checks for.  I think the precedence of these checks can be changed so that we can minimize unnecessary calls. 
For example, it might be better to first check checkAllGamesFull  before checkTeam as it may be more likely that the user(the observer for the game) isn't aware of whether the round is full or not rather than entering a team name that isn't in the bracket(this is because I assume that the observer can see the lists on team names in the bracket on the Teams page). Similarly for validPoints, it's unlikely that the observer will input points that is invalid as he/she is currently watching the game so it might be a good idea to change the order of which checks should get called first.

**Review by Nicknames43 — DISMISSED** [review]
Overall, this pull request looks good. I can see that your implementation follows CA and SOLID. 

I know we've discussed the implementation of the traversal strategies but I'll write my thoughts out in case anyone else uses them in their code. I think that to better follow the open/closed principle of SOLID we should refactor the traversalStrategies package so that the methods of the classes within it are actually within the bracket interface. This would mean that any class that implements the bracket interface be forced to implement these methods which is already required for this use case to work anyways. This would allow for the extension of our program to have more bracket types without having to modify the classes in the traversalStrategies package. 

Other than this in the ChangePointsUC, for the changePoints method, you can implement an if-else if method instead of a bunch of if blocks but this is more of a stylistic change and wouldn't change any functionality since each if has a return statement within them. I will also second the notion that the order of the checks for this same method should be adjusted as Kelly has brought up.

**Review by Nicknames43 — APPROVED** [review]
We discussed this. Same as above

**Review by yibinglu — APPROVED** [review]
Fixed merge conflict in person

**Review by Kelleou — APPROVED** [review]
Approved.

**Pull request merged**
