### PR TITLE
10 feature 10 declare winner of a game

### PR DESCRIPTION
**Pull request by AdK0101**
NOTE: Since I work on three different, similar features (advancing a winner, declaring a winner, and changing the points for a team), and I occasionally pulled from branches other than this one, some of the commits on this branch are not directly related to the development of this feature – partially to test things informally, simply for convenience. However, the main development on this branch was relating to declaring a winner. Also note that when it says there are three participants, that does not mean that the other two group members (Samuel, Nicholas) wrote code for this feature - rather I pulled code into this branch that they wrote for a _different feature._  This can be seen in the commit history. 

This is a pull request for the feature relating to declaring a winner of a game, once it has been completed. All of the backend has more or less been completed. This pull request contains the following new classes in the use case layer: DeclareWinnerUC (the use case interactor), DeclareWinnerID (the input data/request model), DeclareWinnerOD (output data/response model), DeclareWinnerIB (input boundary), and DeclareWinnerOB (output boundary). This was designed to be in line with clean architecture. The input takes the bracket ID, username, and game ID from user input, and is passed into the interactor’s setWinner method (via the output boundary). Here the use case does the following: provided all of the necessary conditions are met, the team that meets the win condition that was set for the bracket, is declared the winner, and the game is set to be completed (gameStatus == true). The output data packages and brings the data out to the presenter. 

I have also made a draft of the controller, and presenter. These may need to be slightly modified once we get a better understanding of the view. But for the time being, it should be a working draft. Finally, I have also implemented a very crude form of persistence (which I have tested informally). The classes related to it are the DeclareWinnerDSID (database request model), which is passed in via the gateway interface to the DeclareWinnerFileWriter, which saves the data. 

Things do add later
1. I have some very minor documentation. I will add more javadocs later. 
2. I have tested informally. But I have not written formal unit tests. I will do that later. 

Other notes: 
1. one design decision I made, was that I allowed for multiple teams to reach the win condition, but only the first team of those would be selected as the winner of the game (under the observer’s discretion). We can change this later if needed. 
2. I deleted a number of files in my branch prior to pull requesting (those that were unnecessary), so my last few commits may show up as having failed the github autograding, even though the code should work fine.

### CODE REVIEW

**Review by yibinglu — DISMISSED** [review]
Overall, this implementation follows CA and SOLID and the use case contains all the main functionalities this feature needs. If I'm not mistaken, it is extremely similar to ChangePoints, just with the declaration of the winner and then passing it into output data. Because it is so similar to ChangePoints and that's the one I reviewed first, I won't bother making the same comments here for the stuff that was repeated. One thing I wanted to ask about was the winnerDeclared attribute. Right now, if !winnerDeclared, it presents an error message "No team has won this game yet", maybe I missed something but what triggers this message? Because otherwise, won't it just keep showing this error repeatedly until a winner is declared at the end? Again, I'll approve this PR, just make sure to communicate any changes you make before we merge it.

**Comment by AdK0101** [comment]
Regarding your question about winnerDeclared. This variable is the result of the determineWinner private method which checks if there are any teams meeting the win condition. This method returns false, if there aren't any meeting that condition, and hence, aren't any teams that can plausibly be declared winner. This should throw an exception. So that's what triggers this message. It should not repeatedly show this error because this method only returns false if there are no teams matching the win condition.

**Review by yibinglu — DISMISSED** [review]
Same change as https://github.com/CSC207-2022F-UofT/course-project-group65/pull/30

**Review by Kelleou — APPROVED** [review]
I can see that your code follows clean architecture as each layer is clearly separated.  I just have a few concerns regarding DeclareWinnerID and DeclareWinnerUC.
For DeclareWinnerID, I noticed that this requires user to input bracketID, gameID, and username. Does this implies that the overseer can see the current bracketID and gameID directly from their screen(which a player wouldn't be able to see)? And for username, does the overseer enter his/her own username or the username of an observer?
For DeclareWinnerUC, I noticed that two of the checks have a very similar function. checkUserPermission and checkObserverAssigned both checks if the user is an observer except checkUserPermission also returns true if the user is an overseer.
Yet in setWinner, a winner is only successfully declared if it passes both checkUserPermission and checkObserverAssigned (which is only true if the user is an Observer in the bracket) so this makes me question why checkUserPermission is necessary as it seems like if checkObserverAssigned returns true, then its already implied that checkUserPermission will return true.

**Comment by AdK0101** [comment]
To your second point, what I'll probably do is once this is in the main branch, I'll restructure those two checks to not be redundant. As to your first point, the gameID can be visible I think - it does not have to be hidden from the player. And the use case does need to know which game is having its winner declared, so that is necessary. As for username it kind of depends on how I design the screen - we could still have that inputted by the user. But in all likelihood, I'll remove the username and bracketID from input data. Thanks for the advice.

**Review by minjaedavidpark — DISMISSED** [review]
Your packaging and code structure follow Clean Architecture, which is great.
For now, I don't really see any problem in your code itself other than what Kelly said she's concerning. 
It seems like you already know what you need to do and fix.
So I will approve it. Thanks for the hard work!

**Review by minjaedavidpark — APPROVED** [review]
tried to solve the merge conflict.

**Review by yibinglu — APPROVED** [review]
Approved for merge conflict

**Review by Kelleou — APPROVED** [review]
Approved to resolve merge conflict

**Pull request merged**
